default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: db_user
  password: db_pass

development:
  <<: *default
  database: app_name_dev

test:
  <<: *default
  database: app_name_test
